# Generated by Django 3.1.7 on 2021-07-06 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210706_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
