# Generated by Django 3.1.7 on 2021-03-27 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210327_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Time',
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
