# Generated by Django 3.1.5 on 2021-01-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='categorys',
            field=models.ManyToManyField(to='restaurant.RestCategory'),
        ),
    ]
