# Generated by Django 3.1.7 on 2021-03-13 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='rest/'),
            preserve_default=False,
        ),
    ]
